const express = require ('express')
const router = express.Router()
const { registerForm, addMember, dashboard, memberInfo, editMemberForm, editMemberInfo, deleteMember, deactivateMember, searching, activateMember, inactiveMembers } = require('../Controllers/userController') 
router.get('/registerForm', registerForm)
router.post('/addMember',addMember)
router.get('/dashboard',dashboard)
router.get('/memberInfo/:id', memberInfo)
router.get('/editMemberInfo/:id', editMemberForm)
router.post('/editMemberInfo/:id',editMemberInfo)
router.delete('/deleteMember/:id', deleteMember)
router.post('/deactivateMember/:id', deactivateMember)
router.post('/activateMember/:id', activateMember)
router.get('/inactiveMembers',inactiveMembers)
router.post('/search', searching)
module.exports = router ;